name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  kiwi: ^4.1.0
  auth:
    path: ../auth
  home:
    path: ../home
  flutter_secure_storage: ^9.0.0
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  kiwi_generator: ^4.1.0

flutter:
